name: Deploy Lambda

on:
  push:
    branches: [main]

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Authenticate with AWS using OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::288761743924:role/github-actions-lambda-role
          aws-region: eu-west-1
      
      # Install Python (for Lambda dependencies)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Zip Lambda code
      - name: Package Lambdas
        run: |
          cd lambdas/
          for dir in */; do
            echo "Zipping $dir..."
            cd "$dir"
            # Install Python deps if requirements.txt exists
            if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt -t ./package
              zip -r9 "../${dir%/}.zip" ./package/
            fi
            # Zip the Lambda code
            zip -g "../${dir%/}.zip" *.py
            cd ..
          done

      - name: Upload to S3
        run: |
          cd lambdas/
          echo "Files to upload: $(ls *.zip)"
          for zipfile in *.zip; do
            aws s3 cp "$zipfile" "s3://lambdacicdtest0123/lambda-zips/$zipfile"
            
            done
            echo "Lambdas uploaded to S3!"

  Terraform_Setup:
    runs-on: ubuntu-latest
    steps:
        # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install GPG
        run: sudo apt-get update && sudo apt-get install -y gnupg

      - name: Decrypt Terraform state
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          cd terraform/
          gpg --batch --yes --passphrase "$GPG_PASSPHRASE" --decrypt terraform.tfstate.gpg > terraform.tfstate

      # Initialize and apply Terraform
      - name: Terraform Apply
        run: |
          cd terraform/
          terraform init
          terraform apply -auto-approve